---

version: "3"

services:
  php:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.php
      args:
        UID: ${USER}
        PHP_VERSION: ${PHP_VERSION}

  nginx:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.nginx
    links:
      - php
    ports:
      - 8000
    labels:
      traefik.frontend.rule: Host:localhost,traefik

  traefik:
    image: bearstech/traefik-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080
      - 80

  client:
    image: bearstech/debian:stretch
    volumes:
      - ./bin/goss:/usr/local/bin/goss
      - ./compose:/goss
    working_dir: /goss
    links:
      - traefik
    command: >
      goss -g traefik_test.yaml validate
      --max-concurrent 4
      --format documentation
