---

version: "3"

services:
  php:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.php
      args:
        UID: ${USER}
        PHP_VERSION: ${PHP_VERSION}

  nginx:
    image: bearstech/nginx:1.14
    volumes:
      - ./compose/nginx.conf:/etc/nginx/sites-enabled/default
    depends_on:
      - php
    ports:
      - 8000
    labels:
      traefik.enable: 'true'
      traefik.http.routers.phpRouter.rule: Host(`traefik`, `localhost`)

  traefik:
    image: bearstech/traefik-dev:2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080
      - 80

  client:
    image: bearstech/debian:stretch
    volumes:
      - ./bin/goss:/usr/local/bin/goss
      - ./compose:/goss
    working_dir: /goss
    depends_on:
      - traefik
    command: >
      goss -g traefik_test.yaml validate
      --max-concurrent 4
      --format documentation
